#!/bin/sh
#
# This script runs when the track is setup.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# set -euxo pipefail
# 
# until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]; do
#     echo "Waiting for instruqt bootstrap to complete"
#     sleep 1
# done
# 
# mkdir -P /source
# useradd -m -s /bin/bash -d /source user
# chown -R user:user /source
# 
# echo "/bin/su - user" >> /root/.bashrc
# 
# usermod -d /source user

exit 0
