#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# grep "bootstrap\.servers" getting-started-cloud.properties | cut -d'=' -f2- | grep "confluent\.cloud:9092"

exit 0;
